#!/bin/bash
#
# Copyright 2011 cloudControl GmbH
#
# s3-image-load is freely distributable under the terms of an MIT-style license. 
#

SCRIPTS=$(dirname $0)
COMMAND=$0

PYTHON="$(which python)"
if [[ -z $PYTHON ]]; then
    echo "You are missing a Python installation! Please install Python first."
    exit 1
fi

$PYTHON ${SCRIPTS}/src/s3-image-download.py $*
